### Test Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "testusername",
    "email": "test@example.com",
    "password": "verystrongpassword"
}

### Test Login user
# @name login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "verystrongpassword"
}

@token = {{login.response.body.token}}

### Test Get Juice
GET http://localhost:8080/api
Content-Type: application/json

### Test admin endpoint
GET http://localhost:8080/api/admin/test
Content-Type: application/json
Authorization: Bearer {{token}}

### Test Order Juice
POST http://localhost:8080/api/order
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        {
            "juice_id": "c183b981-58b3-425e-8f94-17659deec61c",
            "quantity": 2
        },
        {
            "juice_id": "311b5214-ab1b-46bc-98dd-89d24c415bec",
            "quantity": 1
        }
    ]
}

### Test Order Juice wrong id
POST http://localhost:8080/api/order
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        {
            "juice_id": "a1b2c3d4-0000-0000-0000-000000000000",
            "quantity": 2
        }
    ]
}

### Test Get Order History
GET http://localhost:8080/api/order
Content-Type: application/json
Authorization: Bearer {{token}}