### Test Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "testusername",
    "email": "test@example.com",
    "password": "verystrongpassword"
}

### Test Login user
# @name login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "verystrongpassword"
}

@token = {{login.response.body.token}}

### Test Get Juice
GET http://localhost:8080/api
Content-Type: application/json

### Test admin endpoint
GET http://localhost:8080/api/admin/test
Content-Type: application/json
Authorization: Bearer {{token}}

### Test Order Juice
POST http://localhost:8080/api/order
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        {
            "juice_id": "a0c8c419-afaf-4575-93fb-9a72fa2fc20f",
            "quantity": 2
        },
        {
            "juice_id": "caa5aa16-ba24-4472-bd85-2b4178b306dc",
            "quantity": 1
        }
    ]
}