// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addLog = `-- name: AddLog :exec
INSERT INTO audit_logs (id, user_id, action, target_type, target_id, target_name, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AddLogParams struct {
	UserID     uuid.NullUUID
	Action     string
	TargetType string
	TargetID   uuid.NullUUID
	TargetName sql.NullString
	CreatedAt  time.Time
}

func (q *Queries) AddLog(ctx context.Context, arg AddLogParams) error {
	_, err := q.db.ExecContext(ctx, addLog,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.CreatedAt,
	)
	return err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT id, user_id, action, target_type, target_id, target_name, created_at FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetAuditLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
