// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addLog = `-- name: AddLog :exec
INSERT INTO audit_logs (id, user_id, action, target_type, target_id, target_name, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AddLogParams struct {
	UserID     uuid.NullUUID
	Action     string
	TargetType string
	TargetID   uuid.NullUUID
	TargetName sql.NullString
	CreatedAt  time.Time
}

func (q *Queries) AddLog(ctx context.Context, arg AddLogParams) error {
	_, err := q.db.ExecContext(ctx, addLog,
		arg.UserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.CreatedAt,
	)
	return err
}
