// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: juice.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addJuice = `-- name: AddJuice :one
INSERT INTO juice (id, name, description, price, created_at, updated_at, stock)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    now(),
    now(),
    $4
)
RETURNING id, name, description, price, created_at, updated_at, image_url, stock
`

type AddJuiceParams struct {
	Name        string
	Description string
	Price       int32
	Stock       int32
}

func (q *Queries) AddJuice(ctx context.Context, arg AddJuiceParams) (Juice, error) {
	row := q.db.QueryRowContext(ctx, addJuice,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
	)
	var i Juice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Stock,
	)
	return i, err
}

const decrementJuiceStock = `-- name: DecrementJuiceStock :exec
UPDATE juice
SET stock = stock - $1
WHERE id = $2
`

type DecrementJuiceStockParams struct {
	Stock int32
	ID    uuid.UUID
}

func (q *Queries) DecrementJuiceStock(ctx context.Context, arg DecrementJuiceStockParams) error {
	_, err := q.db.ExecContext(ctx, decrementJuiceStock, arg.Stock, arg.ID)
	return err
}

const deleteJuice = `-- name: DeleteJuice :exec
DELETE FROM juice 
WHERE id = $1
`

func (q *Queries) DeleteJuice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteJuice, id)
	return err
}

const getAllJuice = `-- name: GetAllJuice :many
SELECT juice.id, juice.name, juice.description, juice.price, juice.created_at, juice.updated_at, juice.image_url, juice.stock,
COALESCE(AVG(reviews.rating), 0) AS avg_rating,
COUNT(reviews.id) AS reviews_count
FROM juice
LEFT JOIN reviews ON reviews.juice_id = juice.id
GROUP BY juice.id
ORDER BY juice.name ASC
`

type GetAllJuiceRow struct {
	ID           uuid.UUID
	Name         string
	Description  string
	Price        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ImageUrl     string
	Stock        int32
	AvgRating    interface{}
	ReviewsCount int64
}

func (q *Queries) GetAllJuice(ctx context.Context) ([]GetAllJuiceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllJuice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllJuiceRow
	for rows.Next() {
		var i GetAllJuiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.Stock,
			&i.AvgRating,
			&i.ReviewsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJuiceByID = `-- name: GetJuiceByID :one
SELECT id, name, description, price, created_at, updated_at, image_url, stock FROM juice
WHERE id = $1
`

func (q *Queries) GetJuiceByID(ctx context.Context, id uuid.UUID) (Juice, error) {
	row := q.db.QueryRowContext(ctx, getJuiceByID, id)
	var i Juice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Stock,
	)
	return i, err
}

const getJuiceByName = `-- name: GetJuiceByName :many
SELECT id, name, description, price, created_at, updated_at, image_url, stock FROM juice
WHERE name ILIKE $1
`

func (q *Queries) GetJuiceByName(ctx context.Context, name string) ([]Juice, error) {
	rows, err := q.db.QueryContext(ctx, getJuiceByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Juice
	for rows.Next() {
		var i Juice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJuiceDetails = `-- name: GetJuiceDetails :one
SELECT juice.id, juice.name, juice.description, juice.price, juice.created_at, juice.updated_at, juice.image_url, juice.stock,
COALESCE(AVG(reviews.rating), 0) AS avg_rating,
COUNT(reviews.id) AS reviews_count
FROM juice
LEFT JOIN reviews ON reviews.juice_id = juice.id
WHERE name = $1
GROUP BY juice.id
`

type GetJuiceDetailsRow struct {
	ID           uuid.UUID
	Name         string
	Description  string
	Price        int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ImageUrl     string
	Stock        int32
	AvgRating    interface{}
	ReviewsCount int64
}

func (q *Queries) GetJuiceDetails(ctx context.Context, name string) (GetJuiceDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getJuiceDetails, name)
	var i GetJuiceDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Stock,
		&i.AvgRating,
		&i.ReviewsCount,
	)
	return i, err
}

const getJuiceID = `-- name: GetJuiceID :one
SELECT id from juice
WHERE name = $1
`

func (q *Queries) GetJuiceID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getJuiceID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getJuicesByIDs = `-- name: GetJuicesByIDs :many
SELECT name, id, price, stock FROM juice WHERE id = ANY($1::uuid[])
`

type GetJuicesByIDsRow struct {
	Name  string
	ID    uuid.UUID
	Price int32
	Stock int32
}

func (q *Queries) GetJuicesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetJuicesByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJuicesByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJuicesByIDsRow
	for rows.Next() {
		var i GetJuicesByIDsRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJuice = `-- name: UpdateJuice :one
UPDATE juice
SET
    name = $1,
    description = $2,
    price = $3,
    stock = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, name, description, price, created_at, updated_at, image_url, stock
`

type UpdateJuiceParams struct {
	Name        string
	Description string
	Price       int32
	Stock       int32
	ID          uuid.UUID
}

func (q *Queries) UpdateJuice(ctx context.Context, arg UpdateJuiceParams) (Juice, error) {
	row := q.db.QueryRowContext(ctx, updateJuice,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ID,
	)
	var i Juice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
		&i.Stock,
	)
	return i, err
}

const updateJuiceImage = `-- name: UpdateJuiceImage :exec
UPDATE juice
SET image_url = $1
WHERE id = $2
`

type UpdateJuiceImageParams struct {
	ImageUrl string
	ID       uuid.UUID
}

func (q *Queries) UpdateJuiceImage(ctx context.Context, arg UpdateJuiceImageParams) error {
	_, err := q.db.ExecContext(ctx, updateJuiceImage, arg.ImageUrl, arg.ID)
	return err
}
