// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: juice.sql

package database

import (
	"context"
)

const getAllJuice = `-- name: GetAllJuice :many
SELECT id, name, description, price, created_at, updated_at, image_url, stock FROM juice 
ORDER BY created_at ASC
`

func (q *Queries) GetAllJuice(ctx context.Context) ([]Juice, error) {
	rows, err := q.db.QueryContext(ctx, getAllJuice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Juice
	for rows.Next() {
		var i Juice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
