// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	TargetType string
	TargetID   uuid.NullUUID
	TargetName sql.NullString
	CreatedAt  time.Time
}

type Juice struct {
	ID          uuid.UUID
	Name        string
	Description string
	Price       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ImageUrl    string
	Stock       int32
}

type Order struct {
	ID        uuid.UUID
	Total     int32
	CreatedAt time.Time
	UserID    uuid.UUID
}

type OrderItem struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	JuiceID  uuid.UUID
	Quantity int32
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Review struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	JuiceID   uuid.UUID
	Rating    int32
	Comment   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           string
}
