// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, total, created_at, user_id)
VALUES (gen_random_uuid(), $1, NOW(), $2)
RETURNING id, total, created_at, user_id
`

type CreateOrderParams struct {
	Total  int32
	UserID uuid.UUID
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Total, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Total,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, juice_id, quantity)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, order_id, juice_id, quantity
`

type CreateOrderItemParams struct {
	OrderID  uuid.UUID
	JuiceID  uuid.UUID
	Quantity int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem, arg.OrderID, arg.JuiceID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.JuiceID,
		&i.Quantity,
	)
	return i, err
}

const getJuicesByIDs = `-- name: GetJuicesByIDs :many
SELECT id, price FROM juice WHERE id = ANY($1::uuid[])
`

type GetJuicesByIDsRow struct {
	ID    uuid.UUID
	Price int32
}

func (q *Queries) GetJuicesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetJuicesByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJuicesByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJuicesByIDsRow
	for rows.Next() {
		var i GetJuicesByIDsRow
		if err := rows.Scan(&i.ID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
