// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, total, created_at, user_id)
VALUES (gen_random_uuid(), $1, NOW(), $2)
RETURNING id, total, created_at, user_id
`

type CreateOrderParams struct {
	Total  int32
	UserID uuid.UUID
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Total, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Total,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, juice_id, quantity)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, order_id, juice_id, quantity
`

type CreateOrderItemParams struct {
	OrderID  uuid.UUID
	JuiceID  uuid.UUID
	Quantity int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem, arg.OrderID, arg.JuiceID, arg.Quantity)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.JuiceID,
		&i.Quantity,
	)
	return i, err
}

const deleteOrderByOrderID = `-- name: DeleteOrderByOrderID :exec
DELETE FROM orders 
where id = $1
`

func (q *Queries) DeleteOrderByOrderID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderByOrderID, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT orders.id, orders.total, orders.created_at, orders.user_id, users.username FROM orders
JOIN users ON orders.user_id = users.id
ORDER BY orders.created_at DESC
LIMIT 10
OFFSET $1
`

type GetAllOrdersRow struct {
	ID        uuid.UUID
	Total     int32
	CreatedAt time.Time
	UserID    uuid.UUID
	Username  string
}

func (q *Queries) GetAllOrders(ctx context.Context, offset int32) ([]GetAllOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrdersRow
	for rows.Next() {
		var i GetAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Total,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByOrderID = `-- name: GetOrderByOrderID :one
SELECT id, total, created_at, user_id FROM orders 
WHERE id = $1
ORDER BY created_at DESC
LIMIT 5
`

func (q *Queries) GetOrderByOrderID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByOrderID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Total,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT juice_id, quantity, juice.name FROM order_items
JOIN juice ON order_items.juice_id = juice.id
WHERE order_items.order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	JuiceID  uuid.UUID
	Quantity int32
	Name     string
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(&i.JuiceID, &i.Quantity, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, created_at, total FROM orders
WHERE user_id = $1
`

type GetOrdersByUserIDRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Total     int32
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIDRow
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
