// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addReview = `-- name: AddReview :one
INSERT INTO reviews(id, user_id, juice_id, rating, comment)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, juice_id, rating, comment, created_at, updated_at
`

type AddReviewParams struct {
	UserID  uuid.UUID
	JuiceID uuid.UUID
	Rating  int32
	Comment sql.NullString
}

func (q *Queries) AddReview(ctx context.Context, arg AddReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, addReview,
		arg.UserID,
		arg.JuiceID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JuiceID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getJuiceReviews = `-- name: GetJuiceReviews :many
SELECT reviews.id, reviews.user_id, reviews.juice_id, reviews.rating, reviews.comment, reviews.created_at, reviews.updated_at, users.username FROM reviews
JOIN users ON reviews.user_id = users.id
WHERE reviews.juice_id = $1
`

type GetJuiceReviewsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	JuiceID   uuid.UUID
	Rating    int32
	Comment   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
}

func (q *Queries) GetJuiceReviews(ctx context.Context, juiceID uuid.UUID) ([]GetJuiceReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJuiceReviews, juiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJuiceReviewsRow
	for rows.Next() {
		var i GetJuiceReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JuiceID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, user_id, juice_id, rating, comment, created_at, updated_at from reviews
WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JuiceID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
